name: chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  dynamic_color: ^1.6.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.9
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: Rectangle 5.png
  min_sdk_android: 21 # android min sdk min:16, default 21
 