// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrfmRX7jdUeazaOCUJkApINY1ZGN3YAw',
    appId: '1:1049003729202:web:a4b7cf1b9a52d5d01df72b',
    messagingSenderId: '1049003729202',
    projectId: 'chat-paradise-gdsc',
    authDomain: 'chat-paradise-gdsc.firebaseapp.com',
    storageBucket: 'chat-paradise-gdsc.appspot.com',
    measurementId: 'G-4530MGV4XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7CjvaNLLvwJ_Rt4xMs_7lcZL7IkjYmc',
    appId: '1:1049003729202:android:5a2b49a7c543bbd31df72b',
    messagingSenderId: '1049003729202',
    projectId: 'chat-paradise-gdsc',
    storageBucket: 'chat-paradise-gdsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXHMv2_098nzTG8l-GEmZSaaCmJ00usQ',
    appId: '1:1049003729202:ios:56caf6c241c1a71f1df72b',
    messagingSenderId: '1049003729202',
    projectId: 'chat-paradise-gdsc',
    storageBucket: 'chat-paradise-gdsc.appspot.com',
    iosClientId:
        '1049003729202-dsc3tq6bl2aeokm946cmks78an42qu77.apps.googleusercontent.com',
    iosBundleId: 'com.ucdavisgdsc.paradise.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXHMv2_098nzTG8l-GEmZSaaCmJ00usQ',
    appId: '1:1049003729202:ios:56caf6c241c1a71f1df72b',
    messagingSenderId: '1049003729202',
    projectId: 'chat-paradise-gdsc',
    storageBucket: 'chat-paradise-gdsc.appspot.com',
    iosClientId:
        '1049003729202-dsc3tq6bl2aeokm946cmks78an42qu77.apps.googleusercontent.com',
    iosBundleId: 'com.ucdavisgdsc.paradise.chat',
  );
}
